DROP TABLE IF EXISTS USERS;
 
CREATE TABLE USER_ENTITY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(150) NOT NULL,
  password  VARCHAR(150) NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  active INT default 1,
  roles VARCHAR(250) DEFAULT 'user'
);

DROP TABLE IF EXISTS IMAGE_ENTITY;
 
CREATE TABLE IMAGE_ENTITY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  file_name VARCHAR(250),
  file_path VARCHAR(250),
  img_type VARCHAR(250),
  delete_hash_code VARCHAR(100),
  user_id INT
);